# Generated by Django 5.0.4 on 2024-05-01 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AddField(
            model_name='product',
            name='prodapp_url',
            field=models.URLField(default=''),
        ),
    ]
